base_link:
  sensor_kit_base_link:
    x: 0.9
    y: 0.0
    z: 2.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  hesai_front_left_base_link:
    x: 3.373 # Design Value
    y: 0.740 # Design Value
    z: 0.5482
    roll: 0.0 # Design Value
    pitch: 0.0 # Design Value
    yaw: 0.872665 # Design Value
  hesai_front_right_base_link:
    x: 3.373 # Design Value
    y: -0.740 # Design Value
    z: 0.5482
    roll: 0.0 # Design Value
    pitch: 0.0 # Design Value
    yaw: -0.872665 # Design Value
  # velodyne_rear_base_link: #unused
  #   x: -0.358
  #   y: 0.0
  #   z: 1.631
  #   roll: -0.02
  #   pitch: 0.7281317
  #   yaw: 3.141592
  ars548_front_center_base_link:
    x: 3.520 # Design Value
    y: 0.0 # Design Value
    z: 0.6352
    roll: 0.0 # Design Value
    pitch: 0.0 # Design Value
    yaw: 0.0 # Design Value
  ars548_front_right_base_link:
    x: 3.384 # Design Value
    y: -0.7775 # Design Value
    z: 0.410
    roll: 0.0 # Design Value
    pitch: 0.0 # Design Value
    yaw: -1.22173 # Design Value
  ars548_front_left_base_link:
    x: 3.384 # Design Value
    y: 0.7775 # Design Value
    z: 0.410
    roll: 0.0 # Design Value
    pitch: 0.0 # Design Value
    yaw: 1.22173 # Design Value
  ars548_back_center_base_link:
    x: -0.858 # Design Value
    y: 0.0 # Design Value
    z: 0.520
    roll: 0.0 # Design Value
    pitch: 0.0 # Design Value
    yaw: 3.141592 # Design Value
  ars548_back_right_base_link:
    x: -0.782 # Design Value
    y: -0.761 # Design Value
    z: 0.520
    roll: 0.0 # Design Value
    pitch: 0.0 # Design Value
    yaw: -2.0944 # Design Value
  ars548_back_left_base_link:
    x: -0.782 # Design Value
    y: 0.761 # Design Value
    z: 0.520
    roll: 0.0 # Design Value
    pitch: 0.0 # Design Value
    yaw: 2.0944 # Design Value
