/**:
  ros__parameters:
    point_filters: |
      {
        "ring_section_filter": [
        [0, 60,128], [0, 232,300],
        [1, 60,124], [1, 236,300],
        [2, 60,122], [2, 238,300],
        [3, 60,120], [3, 240,300],
        [4, 60,118], [4, 242,300],
        [5, 60,118], [5, 242,300],
        [6, 60,114], [6, 246,300],
        [7, 60,114], [7, 246,300],
        [8, 60,112], [8, 248,300],
        [9, 60,112], [9, 248,300],
        [10, 60,110], [10, 250,300],
        [11, 60,110], [11, 250,300],
        [12, 60,108], [12, 252,300],
        [13, 60,108], [13, 252,300],
        [14, 60,108], [14, 252,300],
        [15, 60,108], [15, 252,300],
        [16, 60,108], [16, 252,300],
        [17, 60,108], [17, 252,300],
        [18, 60,106], [18, 254,300],
        [19, 60,106], [19, 254,300],
        [20, 60,102], [20, 258,300],
        [21, 60,102], [21, 258,300],
        [22, 60,100], [22, 260,300],
        [23, 60,100], [23, 260,300],
        [24, 60,100], [24, 260,300],
        [25, 60,100], [25, 260,300],
        [26, 60,100], [26, 260,300],
        [27, 60,100], [27, 260,300],
        [28, 60,100], [28, 260,300],
        [29, 60,100], [29, 260,300],
        [30, 60,94], [30, 266,300],
        [31, 60,94], [31, 266,300],
        [32, 60,94], [32, 266,300],
        [33, 60,94], [33, 266,300],
        [0, 0, 360],
        [3, 0, 360],
        [6, 0, 360],
        [9, 0, 360],
        [12, 0, 360],
        [15, 0, 360],
        [18, 0, 360],
        [21, 0, 360],
        [24, 0, 360],
        [27, 0, 360],
        [30, 0, 360],
        [33, 0, 360],
        [36, 0, 360],
        [39, 0, 360],
        [42, 0, 360],
        [45, 0, 360],
        [48, 0, 360],
        [51, 0, 360],
        [54, 0, 360],
        [57, 0, 360],
        [60, 0, 360],
        [63, 0, 360],
        [66, 0, 360],
        [69, 0, 360],
        [72, 0, 360],
        [75, 0, 360],
        [78, 0, 360],
        [81, 0, 360],
        [84, 0, 360],
        [87, 0, 360],
        [90, 0, 360],
        [93, 0, 360],
        [96, 0, 360],
        [99, 0, 360],
        [102, 0, 360],
        [105, 0, 360],
        [108, 0, 360],
        [111, 0, 360],
        [114, 0, 360],
        [117, 0, 360],
        [120, 0, 360],
        [123, 0, 360],
        [126, 0, 360]
        ]
      }
