/**:
  ros__parameters:
    point_filters: |
      {
        "ring_section_filter": [
        [0, 60,128], [0, 232,300],
        [1, 60,124], [1, 236,300],
        [2, 60,122], [2, 238,300],
        [3, 60,120], [3, 240,300],
        [4, 60,118], [4, 242,300],
        [5, 60,118], [5, 242,300],
        [6, 60,114], [6, 246,300],
        [7, 60,114], [7, 246,300],
        [8, 60,112], [8, 248,300],
        [9, 60,112], [9, 248,300],
        [10, 60,110], [10, 250,300],
        [11, 60,110], [11, 250,300],
        [12, 60,108], [12, 252,300],
        [13, 60,108], [13, 252,300],
        [14, 60,108], [14, 252,300],
        [15, 60,108], [15, 252,300],
        [16, 60,108], [16, 252,300],
        [17, 60,108], [17, 252,300],
        [18, 60,106], [18, 254,300],
        [19, 60,106], [19, 254,300],
        [20, 60,102], [20, 258,300],
        [21, 60,102], [21, 258,300],
        [22, 60,100], [22, 260,300],
        [23, 60,100], [23, 260,300],
        [24, 60,100], [24, 260,300],
        [25, 60,100], [25, 260,300],
        [26, 60,100], [26, 260,300],
        [27, 60,100], [27, 260,300],
        [28, 60,100], [28, 260,300],
        [29, 60,100], [29, 260,300],
        [30, 60,94], [30, 266,300],
        [31, 60,94], [31, 266,300],
        [32, 60,94], [32, 266,300],
        [33, 60,94], [33, 266,300],
        [1, 0, 360],
        [2, 0, 360],
        [4, 0, 360],
        [5, 0, 360],
        [7, 0, 360],
        [8, 0, 360],
        [10, 0, 360],
        [11, 0, 360],
        [13, 0, 360],
        [14, 0, 360],
        [16, 0, 360],
        [17, 0, 360],
        [19, 0, 360],
        [20, 0, 360],
        [22, 0, 360],
        [23, 0, 360],
        [25, 0, 360],
        [26, 0, 360],
        [28, 0, 360],
        [29, 0, 360],
        [31, 0, 360],
        [32, 0, 360],
        [34, 0, 360],
        [35, 0, 360],
        [37, 0, 360],
        [38, 0, 360],
        [40, 0, 360],
        [41, 0, 360],
        [43, 0, 360],
        [44, 0, 360],
        [46, 0, 360],
        [47, 0, 360],
        [49, 0, 360],
        [50, 0, 360],
        [52, 0, 360],
        [53, 0, 360],
        [55, 0, 360],
        [56, 0, 360],
        [58, 0, 360],
        [59, 0, 360],
        [61, 0, 360],
        [62, 0, 360],
        [64, 0, 360],
        [65, 0, 360],
        [67, 0, 360],
        [68, 0, 360],
        [70, 0, 360],
        [71, 0, 360],
        [73, 0, 360],
        [74, 0, 360],
        [76, 0, 360],
        [77, 0, 360],
        [79, 0, 360],
        [80, 0, 360],
        [82, 0, 360],
        [83, 0, 360],
        [85, 0, 360],
        [86, 0, 360],
        [88, 0, 360],
        [89, 0, 360],
        [91, 0, 360],
        [92, 0, 360],
        [94, 0, 360],
        [95, 0, 360],
        [97, 0, 360],
        [98, 0, 360],
        [100, 0, 360],
        [101, 0, 360],
        [103, 0, 360],
        [104, 0, 360],
        [106, 0, 360],
        [107, 0, 360],
        [109, 0, 360],
        [110, 0, 360],
        [112, 0, 360],
        [113, 0, 360],
        [115, 0, 360],
        [116, 0, 360],
        [118, 0, 360],
        [119, 0, 360],
        [121, 0, 360],
        [122, 0, 360],
        [124, 0, 360],
        [125, 0, 360],
        [127, 0, 360]
        ]
      }
