top_unit_base_link:
  traffic_light_camera_link:
    x: 0.003
    y: 0.063
    z: 0.015
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera0/camera_link:
    x: 0.0235
    y: 0.0
    z: 0.0345
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera1/camera_link:
    x: 0.09841
    y: -0.78172
    z: -0.03618
    roll: 0.0
    pitch: 0.22165
    yaw: -1.047197
  camera2/camera_link:
    x: -0.09841
    y: -0.78172
    z: -0.03618
    roll: 0.0
    pitch: 0.22165
    yaw: -2.094395
  camera4/camera_link:
    x: -0.09841
    y: 0.78172
    z: -0.03618
    roll: 0.0
    pitch: 0.22165
    yaw: 2.094395
  camera5/camera_link:
    x: 0.09841
    y: 0.78172
    z: -0.03618
    roll: 0.0
    pitch: 0.22165
    yaw: 1.047197
  pandar_40p_left_base_link:
    x: 0.0
    y: 0.77827
    z: 0.002
    roll: 0.0
    pitch: 0.0
    yaw: 3.1415
  pandar_qt_left_base_link:
    x: 0.0
    y: 0.7238
    z: -0.1156
    roll: 0.6614798
    pitch: 0.0
    yaw: 3.1415
  pandar_40p_right_base_link:
    x: 0.0
    y: -0.77827
    z: 0.002
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  pandar_qt_right_base_link:
    x: 0.0
    y: -0.7238
    z: -0.1156
    roll: 0.6614798
    pitch: 0.0
    yaw: 0.0
  gnss_left_link:
    x: -0.355
    y: 0.374
    z: 0.0065
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  gnss_right_link:
    x: -0.015
    y: -0.31
    z: 0.0065
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  tamagawa/imu_link:
    x: -0.0195
    y: -0.09185
    z: 0.0165
    roll: 3.14159265359
    pitch: 0.0
    yaw: 0.0
