sensor_kit_base_link:
  velodyne_top_base_link:
    x: 0.000
    y: 0.000
    z: 0.000
    roll: 0.000
    pitch: 0.000
    yaw: 0.000
  pandar_xt32_front_center_base_link:
    x: 1.130
    y: 0.038
    z: -1.400
    roll: -0.000
    pitch: -0.00
    yaw: 1.6225
  tamagawa/imu_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 3.14159
    pitch: 0.0
    yaw: 0.0
