launches:
  - sensor_type: hesai_OT128
    namespace: top
    parameters:
      max_range: 300.0
      sensor_frame: hesai_top
      sensor_ip: 192.168.1.201
      data_port: 2368
      scan_phase: 160.0
      vertical_bins: 128
  - sensor_type: hesai_XT32
    namespace: front_left
    parameters:
      max_range: 300.0
      sensor_frame: hesai_front_left
      sensor_ip: 192.168.1.21
      data_port: 2369
      scan_phase: 50.0
      cloud_min_angle: 50
      cloud_max_angle: 320
      vertical_bins: 16
      horizontal_ring_id: 0
  - sensor_type: hesai_XT32
    namespace: front_right
    parameters:
      max_range: 300.0
      sensor_frame: hesai_front_right
      sensor_ip: 192.168.1.22
      data_port: 2370
      scan_phase: 310.0
      cloud_min_angle: 40
      cloud_max_angle: 310
  - sensor_type: hesai_XT32
    namespace: side_left
    parameters:
      max_range: 10.0
      sensor_frame: hesai_side_left
      sensor_ip: 192.168.1.23
      data_port: 2371
      scan_phase: 90.0
      cloud_min_angle: 90
      cloud_max_angle: 270
  - sensor_type: hesai_XT32
    namespace: side_right
    parameters:
      max_range: 10.0
      sensor_frame: hesai_side_right
      sensor_ip: 192.168.1.24
      data_port: 2372
      scan_phase: 270.0
      cloud_min_angle: 90
      cloud_max_angle: 270

preprocessor:
  input_topics:
    - /sensing/lidar/top/pointcloud_before_sync
    - /sensing/lidar/side_left/pointcloud_before_sync
    - /sensing/lidar/side_right/pointcloud_before_sync
    - /sensing/lidar/front_left/pointcloud_before_sync
    - /sensing/lidar/front_right/pointcloud_before_sync
  input_offset:
    - 0.035
    - 0.025
    - 0.025
    - 0.025
    - 0.025
  timeout_sec: 0.095
  input_twist_topic_type: twist
  publish_synchronized_pointcloud: true
