# Description:
#   name: diag name
#   is_active: Force update or not
#   status: diag status set by dummy diag publisher "OK, Warn, Error, Stale"
#
# Note:
#
# default values are:
#   is_active: "true"
#   status: "OK"
---
/**:
  ros__parameters:
    required_diags:
      # velodyne
      velodyne_connection: default
      velodyne_temperature: default
      velodyne_rpm: default

      # livox
      livox_connection: default
      livox_fan_status: default
      livox_firmware_status: default
      livox_internal_voltage: default
      livox_motor_status: default
      livox_service_life: default
      livox_temperature: default

      # imu
      gyro_bias_estimator: default
