/**:
  ros__parameters:
    point_filters: |
      {
        "ring_section_filter": [
        [0, 0, 360],
        [1, 0, 360],
        [2, 0, 170],[2, 192, 300],
        [3, 0, 160],[3, 199.5, 300],
        [4, 0, 155],[4, 203, 300],
        [5, 0, 152],[5, 206, 217],[5, 220, 300],
        [6, 0, 146],[6, 217, 300],
        [7, 0, 143],[7, 235, 300],
        [8, 0, 139],[8, 228.5, 300],
        [9, 0, 135],[9, 228.5, 300],
        [10, 0, 133],[10, 235, 300],
        [11, 0, 132],[11, 235, 300],
        [12, 0, 131],[12, 235, 300],
        [13, 0, 129],[13, 235, 300],
        [14, 0, 127],[14, 235, 300],
        [15, 0, 126],[15, 235, 300],
        [16, 0, 124],[16, 235, 300],
        [17, 0, 122],[17, 235, 300],
        [18, 0, 121],[18, 235, 300],
        [19, 0, 120],[19, 235, 300],
        [20, 0, 119],[20, 235, 300],
        [21, 0, 118],[21, 235, 300],
        [22, 0, 117],[22, 235, 300],
        [23, 0, 116],[23, 235, 300],
        [24, 0, 115],[24, 235, 300],
        [25, 0, 114],[25, 235, 300],
        [26, 0, 113],[26, 235, 300],
        [27, 0, 112],[27, 235, 300],
        [28, 0, 111],[28, 242, 300],
        [29, 0, 110],[29, 242, 300],
        [30, 0, 110],[30, 242, 300],
        [31, 0, 109],[31, 244, 265],
        [32, 0, 109],[32, 244, 265],
        [33, 0, 108],[33, 244, 265],
        [34, 0, 108],[34, 244, 265],
        [35, 0, 107],[35, 244, 265],
        [36, 0, 107],[36, 244, 265],
        [37, 0, 106],[37, 244, 265],
        [38, 0, 106],[38, 244, 265],
        [39, 0, 105],[39, 244, 265],
        [40, 0, 105],[40, 244, 265],
        [41, 0, 104],[41, 244, 265],
        [42, 0, 104],[42, 244, 265],
        [43, 0, 103],[43, 244, 265],
        [44, 0, 102],
        [45, 0, 101],
        [46, 0, 96],
        [47, 0, 95],
        [48, 0, 95],
        [49, 0, 94],
        [50, 0, 93],
        [51, 0, 93],
        [1, 0, 360],
        [2, 0, 360],
        [4, 0, 360],
        [5, 0, 360],
        [7, 0, 360],
        [8, 0, 360],
        [10, 0, 360],
        [11, 0, 360],
        [13, 0, 360],
        [14, 0, 360],
        [16, 0, 360],
        [17, 0, 360],
        [19, 0, 360],
        [20, 0, 360],
        [22, 0, 360],
        [23, 0, 360],
        [25, 0, 360],
        [26, 0, 360],
        [28, 0, 360],
        [29, 0, 360],
        [31, 0, 360],
        [32, 0, 360],
        [34, 0, 360],
        [35, 0, 360],
        [37, 0, 360],
        [38, 0, 360],
        [40, 0, 360],
        [41, 0, 360],
        [43, 0, 360],
        [44, 0, 360],
        [46, 0, 360],
        [47, 0, 360],
        [49, 0, 360],
        [50, 0, 360],
        [52, 0, 360],
        [53, 0, 360],
        [55, 0, 360],
        [56, 0, 360],
        [58, 0, 360],
        [59, 0, 360],
        [61, 0, 360],
        [62, 0, 360],
        [64, 0, 360],
        [65, 0, 360],
        [67, 0, 360],
        [68, 0, 360],
        [70, 0, 360],
        [71, 0, 360],
        [73, 0, 360],
        [74, 0, 360],
        [76, 0, 360],
        [77, 0, 360],
        [79, 0, 360],
        [80, 0, 360],
        [82, 0, 360],
        [83, 0, 360],
        [85, 0, 360],
        [86, 0, 360],
        [88, 0, 360],
        [89, 0, 360],
        [91, 0, 360],
        [92, 0, 360],
        [94, 0, 360],
        [95, 0, 360],
        [97, 0, 360],
        [98, 0, 360],
        [100, 0, 360],
        [101, 0, 360],
        [103, 0, 360],
        [104, 0, 360],
        [106, 0, 360],
        [107, 0, 360],
        [109, 0, 360],
        [110, 0, 360],
        [112, 0, 360],
        [113, 0, 360],
        [115, 0, 360],
        [116, 0, 360],
        [118, 0, 360],
        [119, 0, 360],
        [121, 0, 360],
        [122, 0, 360],
        [124, 0, 360],
        [125, 0, 360],
        [127, 0, 360]
        ]
      }
